spring.application.name=BootMVCProj03-SeasonFinderApp
#view Resolver App
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
#conext path for application embedded server
server.servlet.context-path=/SeasonApp
#Embedded Server port number
server.port=7799